[2023-06-24 11:06:19] INFO : => COVID PROJECT <= (main.py:181)
[2023-06-24 11:06:19] INFO : Starting ETL for Covid Data... (main.py:201)
[2023-06-24 11:06:19] INFO : => STARTING EXTRACT... (main.py:49)
[2023-06-24 11:06:19] INFO : Data read successfully from the local CSV file. (extract.py:50)
[2023-06-24 11:06:19] INFO : Done reading CSV data from local. (main.py:53)
[2023-06-24 11:06:19] INFO : Extract process for Covid - CPU usage 8.5% (main.py:68)
[2023-06-24 11:06:19] INFO : Extract process for Covid - function took : 0.0 seconds (main.py:69)
[2023-06-24 11:06:19] INFO : => STARTING TRANSFORM... (main.py:75)
[2023-06-24 11:06:19] INFO : Starting transform with nyt_cases_counties... (main.py:79)
[2023-06-24 11:06:19] INFO : Done transforming nyt_cases_counties. (main.py:81)
[2023-06-24 11:06:19] INFO : Transform process for Covid - CPU usage 0.0% (main.py:90)
[2023-06-24 11:06:19] INFO : Transform process for Covid - function took : 0.01 seconds (main.py:91)
[2023-06-24 11:06:19] INFO : => STARTING VALIDATE... (main.py:97)
[2023-06-24 11:06:19] INFO : Starting data validation with nyt_cases_counties... (main.py:99)
[2023-06-24 11:06:19] WARNING : Data test cases_vs_deaths failed. Death counts cannot exceed case counts. (validate.py:157)
[2023-06-24 11:06:19] DEBUG : Data test unique_records passed. (validate.py:153)
[2023-06-24 11:06:19] WARNING : Data test no_nulls_test failed. All values are expected to be non-null. (validate.py:157)
[2023-06-24 11:06:19] DEBUG : Data test cases_range_test passed. (validate.py:153)
[2023-06-24 11:06:19] WARNING : Data test deaths_range_test failed. Deaths must be non-negative and <= 100K. (validate.py:157)
[2023-06-24 11:06:19] CRITICAL : 2/5 tests passed. (validate.py:167)
[2023-06-24 11:06:19] INFO : validate info saved successfully to data/validate_info_data/covid_validate_info_20230624.csv. (validate.py:130)
[2023-06-24 11:06:19] INFO : Validation process for Covid - CPU usage 5.6% (main.py:107)
[2023-06-24 11:06:19] INFO : Validation process for Covid - function took : 0.01 seconds (main.py:108)
[2023-06-24 11:06:19] INFO : => STARTING LOAD... (main.py:113)
[2023-06-24 11:06:19] INFO : Saving nyt_cases_counties data to local... (main.py:114)
[2023-06-24 11:06:19] INFO : Data saved successfully to data/save_data/covid_20230624.csv. (load.py:52)
[2023-06-24 11:06:19] INFO : Connected to MySQL database... (database_config.py:85)
[2023-06-24 11:06:19] INFO : covid_db database is created. (database_config.py:181)
[2023-06-24 11:06:19] INFO : covid table is created in covid_db (database_config.py:206)
[2023-06-24 11:06:19] INFO : Data has been loaded to covid_db.covid (database_config.py:234)
[2023-06-24 11:06:19] INFO : nyt_cases_counties data saved to local. (main.py:118)
[2023-06-24 11:06:19] INFO : Load process for Covid - CPU usage 7.2% (main.py:122)
[2023-06-24 11:06:19] INFO : Load process for Covid - function took : 0.12 seconds (main.py:123)
[2023-06-24 11:06:19] INFO : => STARTING CREATE DATA LOGS... (main.py:133)
[2023-06-24 11:06:19] INFO : Starting create data logs (main.py:134)
[2023-06-24 11:06:19] INFO : Data saved successfully to covid_logs.csv . (dataframe_logs.py:108)
[2023-06-24 11:06:19] INFO : Connected to MySQL database... (database_config.py:85)
[2023-06-24 11:06:19] INFO : covid_db database already exists. (database_config.py:183)
[2023-06-24 11:06:19] INFO : covid_logs table is created in covid_db (database_config.py:206)
[2023-06-24 11:06:19] INFO : Data has been loaded to covid_db.covid_logs (database_config.py:234)
[2023-06-24 11:06:19] INFO : Done creating data logs (main.py:137)
[2023-06-24 11:06:19] INFO : => SESSION SUMMARY... (main.py:140)
[2023-06-24 11:06:19] INFO : RAM memory 64.5% used (main.py:144)
[2023-06-24 11:06:19] INFO : Average CPU usage 5.325% (main.py:145)
[2023-06-24 11:06:19] INFO : Multiple threads took : 0.21 seconds (main.py:146)
[2023-06-24 11:06:19] INFO : => SEND DATA VALIDATION EMAIL... (main.py:149)
[2023-06-24 11:06:19] INFO : data/validate_info_data/covid_validate_info_20230624.csv copied to the data/email-data successfully. (email_config.py:68)
[2023-06-24 11:06:19] INFO : data/log_info_data/covid_logs_20230624.log copied to the data/email-data successfully. (email_config.py:68)
[2023-06-24 11:06:19] INFO : Log file 'covid_logs_20230624.log' converted to text file 'covid_logs_20230624.txt' successfully. (email_config.py:126)
[2023-06-24 11:06:19] INFO : Log files processed successfully. (email_config.py:153)
[2023-06-24 11:06:19] INFO : Log files deleted successfully. (email_config.py:181)
